substitutions:
  device_name: kitchen

sensor:
  - platform: scd4x
    co2:
      name: "Kitchen CO2"
    temperature:
      name: "Kitchen Temperature"
    humidity:
      name: "Kitchen Humidity"

<<: !include base/common.yaml
<<: !include base/pi_pico.yaml
